---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: revomve the httpd rpm
    yum: name=httpd
    state: absent
#  - name: start the httpd service
#    service: name=httpd state=started
#  - name: Open port 80
#    firewalld: service=http permanent=true state=enabled
#  - name: start the firewalld service
#    service: name=firewalld state=restarted
