---
# Setup LAMP Stack
- hosts: all
  tasks:
    - name: install lamp stack
      become: yes
      yum: name={{ item }} state=present
      with_items:
        - httpd
        - httpd-devel
        - mariadb.x86_64
        - mariadb-server.x86_64
        - mariadb-devel.x86_64
        - php
        - php-devel
        - php-mysql
      tags: setup

    - name: start services
      service: name={{ item }} state=running enabled=yes
      become: yes
      with_items:
        - httpd
        - mariadb
        - telnet
        - zip
      tags: setup

    - name: deploy index.html
      sudo: yes
      copy: src=/tmp/lamp/index.html dest=/var/www/html/index.html
      become: yes
      tags: setup
    
    - name: install python
      yum:
        name: python
        state: latest
      become: yes
      tags: setup

    
