---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: start the httpd service
    service: name=httpd state=stop
  - name: remove the httpd rpm
    yum: name=httpd
    state: absent
